GET http://localhost:5182/games

###
GET http://localhost:5182/games/2

###
POST http://localhost:5182/games
Content-Type: application/json

{
    "Title": "The Legend of Zelda: Breath of the Wild",
    "description": "An open-world action-adventure game developed and published by Nintendo.",
    "price": 599.99,
    "genre": "Action-Adventure"
}

###
PUT http://localhost:5182/games/2
Content-Type: application/json

{
    "title": "Mortal Kombat 11",
    "description": "A fighting game developed by NetherRealm Studios.",
    "price": 29.99,
    "genre": ""
}

###
DELETE http://localhost:5182/games/4